### ISSUE TITLE
Save Configurations

### ISSUE THREAD

**Issue by GOATIOO** [MattJeanes/Joystick-Module#25]
I set up my controller binds but is there a way to save them? 
I restarted my game and the configuration was gone.

**Comment by MattJeanes** [comment]
The addon is designed to save and load joystick binds set in the joyconfig menu, although it appears to do this on game shut down rather than offering a save button. The ShutDown hook sometimes doesn't get called if the game hard exits (crashes) or in a couple of other scenarios so I imagine this is why it didn't save. You can manually save after changing the settings by running this in the console:

`lua_run_cl jcon.Save()`

Assuming no errors come from that you should be all good.

**Comment by GOATIOO** [comment]
Thanks

**Comment by GOATIOO** [comment]
ever since I did this the addon cannot detect the controller

**Comment by MattJeanes** [comment]
Try deleting `data/joyconfig.txt` that should clear the save file

**Comment by GOATIOO** [comment]
Where is that located?

**Comment by GOATIOO** [comment]
Is it joyconfig lua file?

**Comment by GOATIOO** [comment]
It is still not detecting my controller

**Comment by MattJeanes** [comment]
No it is in garrysmod/data do not delete the joyconfig.lua file

**Comment by GOATIOO** [comment]
I deleted the joyconfig text file but it is still not detecting my
controller.

**Comment by GOATIOO** [comment]
It worked fine at first but now it just won't connect.
